modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="cookery"
version="1.0.0.1"
displayName="Cookery Plus"
credits="Created by MagicalAlexey, with the support of Chiffon Medal"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cookery-plus"
updateJSONURL="https://raw.githubusercontent.com/Hexagon-Studio/Cookery-Plus/main/changelog.json"
logoFile="logo.png"
authors="Hexagon Studio"
description='''
Cookery Plus is a mod that adds new cooking mechanics and new types of food to Minecraft  
'''

[[dependencies.cookery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




